# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Var Logic
email: charles@var-logic.com
description: > # this means to ignore newlines until "baseurl:"
  At Var-Logic view a portfolio of games made by Charlie Ters
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://var-logic.com" # the base hostname & protocol for your site
twitter_username: Var-Logic
github_username:  Var-Logic

# Build settings
markdown: kramdown

include: ['_pages']
